modLoader="javafml"
loaderVersion="[28,)"
license=" "

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    side="BOTH"
