modLoader="javafml"
loaderVersion="[28,)"
license=" "

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="ee_man"
displayURL="https://github.com/vanym/paniclecraft"
description="Create, Play or Draw and Clean up After"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    side="BOTH"
